//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace JANVI_TEST.EDM
{
    using System;
    using System.Collections.Generic;

    public partial class Employee
    {
        public int e_id { get; set; }

        [Required(ErrorMessage = "Enter User Name")]
        [StringLength(10, MinimumLength = 3, ErrorMessage = "Length Between 3 to 10 char..")]
        public string e_name { get; set; }
        [Required(ErrorMessage ="Enter Address")]
        [DataType(DataType.MultilineText)]
        public string e_add { get; set; }
        [Required]
        [RegularExpression(@"^[0][1-9]\d{9}$|^[1-9]\d{9}$", ErrorMessage = "Enter Valid Mobile Number..")]
        public string e_mob { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public string e_dob { get; set; }
        [Required]
        public string e_gender { get; set; }
        public string e_profile { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string e_email { get; set; }
        [Required]
        [StringLength(10, MinimumLength = 5, ErrorMessage = "Length Between 5 to 10 char..")]
        public string e_password { get; set; }
        public Nullable<int> country_id { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
